name: 'Git Status Action'
description: "An action that checks out the repository and runs 'git status'."
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run git status
        run: git status

      - name: Run a command
        run: echo "Hello There"
